version: '3.8'
services:
  app:
    container_name: parcial
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    networks:
      - my_network
networks:
  my_network:

